---
apiVersion: v1
kind: Service
metadata:
  name: petclinic-web
  labels:
    app: petclinic-web
spec:
  ports:
    - port: 8081
      targetPort: 8080
      name: petclinic-web
  selector:
    app: petclinic-web
  type: LoadBalancer
---
apiVersion: apps/v1beta1
kind: Deployment
metadata:
  name: petclinic-web
  labels:
    app: petclinic-web
spec:
  template:
    metadata:
      labels:
        app: petclinic-web
    spec:
      containers:
      - name: petclinic-web
        image: harbor.pks.pvtl.eu/spinnaker/spring-petclinic:latest
        imagePullPolicy: Always
        ports:
        - containerPort: 8080
          name: petclinic-web
